#!/usr/bin/env python3

import datetime
import json
import random
import string
import sys
import tempfile
import unittest

from ..util import *

NOW = datetime.datetime.today().strftime(DUEDATE_FMT)


def random_string(n=10):
    return ''.join(random.choice(string.ascii_lowercase + string.digits)
                   for i in range(n))


class TempFile:
    def __init__(self):
        self._f = tempfile.NamedTemporaryFile(mode='w', suffix='.mucs')
        self.name = self._f.name

    def __enter__(self):
        self._f.__enter__()
        return self

    def __exit__(self, *args, **kwargs):
        self._f.__exit__(*args, **kwargs)

    def __str__(self):
        return "TempFile(name='%s')" % self.name

    # @property
    # def name(self):
        # return self._f.name

    def write(self, data):
        self._f.write(data)
        self._f.flush()


if __name__ == '__main__':
    unittest.main()
