#!/bin/bash

set -e

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Make sure dependencies are installed
whereis make lcov genhtml &>/dev/null

pushd "$HERE" >/dev/null

    make clean
    make -j8 test COVERAGE=1
    ./runtests
    mkdir -p coverage
    lcov -c --no-external -b src -d build/src -o coverage/report.info
    genhtml --legend --function-coverage --demangle-cpp coverage/report.info -o coverage

popd >/dev/null
