function(_bin_dep_status BIN_NAME MSG)
    message(STATUS "Check for binary dependency: ${BIN_NAME}${MSG}")
endfunction()

function(check_binary_dependency DEST_VAR BIN_NAME)
    message("check_binary_dependency(${ARGV})")
    if(${DEST_VAR})
        return()
    endif()
    _bin_dep_status("${BIN_NAME}" "")
    find_file("${DEST_VAR}" "${BIN_NAME}")
    if("${${DEST_VAR}}" STREQUAL "${DEST_VAR}-NOTFOUND")
        message(FATAL_ERROR "Unable to find binary file for required dependency: ${BIN_NAME}")
    else()
        _bin_dep_status("${BIN_NAME}" " -- found")
    endif()
endfunction()
