function(_bin_dep_status BIN_NAME MSG)
    message(STATUS "Finding dependency: ${BIN_NAME}${MSG}")
endfunction()

function(find_dependency DEST_VAR BIN_NAME)
    if(${DEST_VAR})
        return()
    endif()
    _bin_dep_status("${BIN_NAME}" "")
    find_file("${DEST_VAR}" "${BIN_NAME}")
    if("${${DEST_VAR}}" STREQUAL "${DEST_VAR}-NOTFOUND")
        message(FATAL_ERROR "Unable to find required dependency: ${BIN_NAME}")
    else()
        _bin_dep_status("${BIN_NAME}" " - found (${${DEST_VAR}})")
    endif()
endfunction()
