#!/usr/bin/env bash

set -e

. /usr/share/Modules/init/bash
module load gcc/gcc-10.1.0 &>/dev/null

COLORGCC_PATH='@_COLORGCC_PATH@'
"$COLORGCC_PATH" "$@" \
    -std=c11 -Wall -Werror -g \
    -I/group/cs1050/include \
    -L/group/cs1050/lib \
    -lm \
