#!/usr/bin/env bash

should_use_make() {
    # Exit successfully if all are true:
    # - we are in a git repo
    git rev-parse --is-inside-work-tree &>/dev/null || return 1
    # - the origin URL comes from github user JimRies1966
    local origin="$(git remote get-url origin 2>/dev/null)"
    [[ "$origin" =~ github\.com/JimRies1966 ]] || return 1
    # - a file named Makefile exists
    [[ -f Makefile ]] || return 1
}

if should_use_make; then
    make
else
    gcc -std=c11 -g -Wall -Werror "$@" -lm
fi
