#!/usr/bin/env bash

HERE="$(dirname "$(readlink -f "$0")")"

count_dir() {
    find "$@" -type f -exec wc -l {} + | awk 'END{print $1}'
}

cd "$HERE/.."

src_lines=$(count_dir src)
test_lines=$(count_dir test)
total_lines=$(( src_lines + test_lines ))

echo "  Source: $src_lines"
echo "    Test: $test_lines"
echo "   Total: $total_lines"
