#!/usr/bin/env bash

set -e

if [ $# -ne 1 ]; then
    cat >&2 <<HERE
Usage: $0 ROSTER_DIR

Use fzf to search the roster.
HERE
    exit 1
fi

ROSTER_D="$1"

find "$ROSTER_D" -type f | while read fn; do
    lab_id="$(basename "$fn")"
    awk -v lab_id="$lab_id" -v OFS=, '{print lab_id,$1}' "$fn"
done | '@_FZF_PATH@' --border=rounded
