#!/usr/bin/env bash

set -e

ROSTER_D='@_PREFIX@/roster.d'

find "$ROSTER_D" -type f -printf '%f %p\n' | while read id fn; do
    awk -v OFS=, "{print $id,\$1}" "$fn"
done | '@_FZF_PATH@' --border=rounded
