#!/usr/bin/env bash

# TODO: download real roster

exec >/dev/null 2>&1

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CFG="$HERE/../mucs/etc/mucs/cs1050.json"

rand_letter() {
    LETTERS=abcde
    echo "${LETTERS:$(( RANDOM % ${#LETTERS} )):1}"
}

template="$(cat roster.xls |
    tr -d '[:space:]' |
    grep -Eo '(<td>[^<]*</td>){5}' |
    sed -E 's#^.*<td>([^@]+)[^<]+</td>$#"\1":"%s",#'
)"
nlines="$(wc -l <<< "$template" | awk '{print $1}')"

subs=( $(for ((i=0; i<nlines; i++)); do rand_letter; done) )

roster="$(printf "$template" "${subs[@]}")"
config="$(jq --indent 4 -M ".roster={$roster}" < "$CFG")"
echo "$config" > "$CFG"
