#!/usr/bin/env bash
#
# Finish installation, do stuff that cmake can't.
#

set -e

status() {
    MSG="$1"
    echo "$MSG"
}

status_done() {
    echo "$MSG - done"
    unset MSG
}

bin_exists() {
    [ -f "$1" -a -x "$1" ]
}

cleanup_trap() {
    trap "$1" HUP TERM INT EXIT
}

echo '==========[ POST INSTALL SCRIPT ]==========' >&2

cd '@_PREFIX@'

mkdir -p config.d roster.d submissions

# Do these in subshells so that the trap executes sooner rather than later

(
    bin_exists scripts/colorgcc.pl && exit
    status 'Downloading colorgcc'
    URL='https://github.com/colorgcc/colorgcc/archive/1.4.5.tar.gz'
    ARCHIVE="$(mktemp /tmp/colorgcc-archive.XXXXXX)"
    cleanup_trap 'rm -f "$ARCHIVE"'
    curl -sSL "$URL" -o "$ARCHIVE"
    tar -xzf "$ARCHIVE" -C scripts \
        --strip-components=1 --wildcards 'colorgcc-*/colorgcc.pl'
    status_done
)

(
    bin_exists scripts/fzf && exit
    status 'Downloading fzf'
    URL='https://github.com/junegunn/fzf/releases/download/0.26.0/fzf-0.26.0-linux_amd64.tar.gz'
    ARCHIVE="$(mktemp /tmp/fzf-archive.XXXXXX)"
    cleanup_trap 'rm -f "$ARCHIVE"'
    curl -sSL "$URL" -o "$ARCHIVE"
    tar -xzf "$ARCHIVE" -C scripts
    status_done
)

# Create a venv for the gen-roster script and install its dependencies
VENV='@_SCRIPTS_VENV@'
if [ ! -d "$VENV" ]; then
    status 'Creating venv for scripts'
    python3 -m venv --system-site-packages "$VENV"
    status_done
fi
status 'Installing venv dependencies for scripts'
. "$VENV/bin/activate"
pip3 install -r '@_SCRIPTS_VENV_REQUIREMENTS@'
deactivate
status_done

# Fix file permisisons
# The chgrp command clears special permission bits (setuid, setgid, and sticky)
#   so find is used to chgrp then re-enable setgid

status 'Fixing permissions'
CHGRP_TARGETS='schema.json bin scripts config.d roster.d'
# Change group on files with setgid enabled
find $CHGRP_TARGETS ! -type l -perm -g=s \
    -exec chgrp cs1050-ta {} + \
    -exec chmod g+s {} + || true
# Change group on files with setgid NOT enabled
find $CHGRP_TARGETS ! -type l ! -perm -g=s \
    -exec chgrp cs1050-ta {} + || true
status_done
